import React from 'react';
import { Button, Modal } from 'antd';
import SeatCreate from '../components/SeatCreate';
import SeatUpdate from '../components/SeatUpdate';

const dataJson = [
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 1,
    seatY: 1,
    rowIndex: 1,
    columnIndex: 1,
    status: '1',
    id: 'seat-1-1',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 1,
    seatY: 2,
    rowIndex: 1,
    columnIndex: 2,
    status: '1',
    id: 'seat-1-2',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 1,
    seatY: 3,
    rowIndex: 1,
    columnIndex: 3,
    status: '1',
    id: 'seat-1-3',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 1,
    seatY: 4,
    rowIndex: 1,
    columnIndex: 4,
    status: '1',
    id: 'seat-1-4',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 1,
    seatY: 5,
    rowIndex: 1,
    columnIndex: 5,
    status: '1',
    id: 'seat-1-5',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 1,
    seatY: 6,
    rowIndex: 1,
    columnIndex: 6,
    status: '1',
    id: 'seat-1-6',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 1,
    seatY: 7,
    rowIndex: 1,
    columnIndex: 7,
    status: '1',
    id: 'seat-1-7',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 1,
    seatY: 8,
    rowIndex: 1,
    columnIndex: 8,
    status: '1',
    id: 'seat-1-8',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 1,
    seatY: 9,
    rowIndex: 1,
    columnIndex: 9,
    status: '1',
    id: 'seat-1-9',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 1,
    seatY: 10,
    rowIndex: 1,
    columnIndex: 10,
    status: '1',
    id: 'seat-1-10',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 2,
    seatY: 1,
    rowIndex: 2,
    columnIndex: 1,
    status: '1',
    id: 'seat-2-1',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 2,
    seatY: 2,
    rowIndex: 2,
    columnIndex: 2,
    status: '1',
    id: 'seat-2-2',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 2,
    seatY: 3,
    rowIndex: 2,
    columnIndex: 3,
    status: '1',
    id: 'seat-2-3',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 2,
    seatY: 4,
    rowIndex: 2,
    columnIndex: 4,
    status: '1',
    id: 'seat-2-4',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 2,
    seatY: 5,
    rowIndex: 2,
    columnIndex: 5,
    status: '1',
    id: 'seat-2-5',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 2,
    seatY: 6,
    rowIndex: 2,
    columnIndex: 6,
    status: '1',
    id: 'seat-2-6',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 2,
    seatY: 7,
    rowIndex: 2,
    columnIndex: 7,
    status: '1',
    id: 'seat-2-7',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 2,
    seatY: 8,
    rowIndex: 2,
    columnIndex: 8,
    status: '1',
    id: 'seat-2-8',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 2,
    seatY: 9,
    rowIndex: 2,
    columnIndex: 9,
    status: '1',
    id: 'seat-2-9',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 2,
    seatY: 10,
    rowIndex: 2,
    columnIndex: 10,
    status: '1',
    id: 'seat-2-10',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 3,
    seatY: 1,
    rowIndex: 3,
    columnIndex: 1,
    status: '1',
    id: 'seat-3-1',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 3,
    seatY: 2,
    rowIndex: 3,
    columnIndex: 2,
    status: '1',
    id: 'seat-3-2',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 3,
    seatY: 3,
    rowIndex: 3,
    columnIndex: 3,
    status: '1',
    id: 'seat-3-3',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 3,
    seatY: 4,
    rowIndex: 3,
    columnIndex: 4,
    status: '1',
    id: 'seat-3-4',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 3,
    seatY: 5,
    rowIndex: 3,
    columnIndex: 5,
    status: '1',
    id: 'seat-3-5',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 3,
    seatY: 6,
    rowIndex: 3,
    columnIndex: 6,
    status: '1',
    id: 'seat-3-6',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 3,
    seatY: 7,
    rowIndex: 3,
    columnIndex: 7,
    status: '1',
    id: 'seat-3-7',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 3,
    seatY: 8,
    rowIndex: 3,
    columnIndex: 8,
    status: '1',
    id: 'seat-3-8',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 3,
    seatY: 9,
    rowIndex: 3,
    columnIndex: 9,
    status: '1',
    id: 'seat-3-9',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 3,
    seatY: 10,
    rowIndex: 3,
    columnIndex: 10,
    status: '1',
    id: 'seat-3-10',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 4,
    seatY: 1,
    rowIndex: 4,
    columnIndex: 1,
    status: '1',
    id: 'seat-4-1',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 4,
    seatY: 2,
    rowIndex: 4,
    columnIndex: 2,
    status: '1',
    id: 'seat-4-2',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 4,
    seatY: 3,
    rowIndex: 4,
    columnIndex: 3,
    status: '1',
    id: 'seat-4-3',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 4,
    seatY: 4,
    rowIndex: 4,
    columnIndex: 4,
    status: '1',
    id: 'seat-4-4',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 4,
    seatY: 5,
    rowIndex: 4,
    columnIndex: 5,
    status: '1',
    id: 'seat-4-5',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 4,
    seatY: 6,
    rowIndex: 4,
    columnIndex: 6,
    status: '1',
    id: 'seat-4-6',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 4,
    seatY: 7,
    rowIndex: 4,
    columnIndex: 7,
    status: '1',
    id: 'seat-4-7',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 4,
    seatY: 8,
    rowIndex: 4,
    columnIndex: 8,
    status: '1',
    id: 'seat-4-8',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 4,
    seatY: 9,
    rowIndex: 4,
    columnIndex: 9,
    status: '1',
    id: 'seat-4-9',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 4,
    seatY: 10,
    rowIndex: 4,
    columnIndex: 10,
    status: '1',
    id: 'seat-4-10',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 5,
    seatY: 1,
    rowIndex: 5,
    columnIndex: 1,
    status: '1',
    id: 'seat-5-1',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 5,
    seatY: 2,
    rowIndex: 5,
    columnIndex: 2,
    status: '1',
    id: 'seat-5-2',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 5,
    seatY: 3,
    rowIndex: 5,
    columnIndex: 3,
    status: '1',
    id: 'seat-5-3',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 5,
    seatY: 4,
    rowIndex: 5,
    columnIndex: 4,
    status: '1',
    id: 'seat-5-4',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 5,
    seatY: 5,
    rowIndex: 5,
    columnIndex: 5,
    status: '1',
    id: 'seat-5-5',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 5,
    seatY: 6,
    rowIndex: 5,
    columnIndex: 6,
    status: '1',
    id: 'seat-5-6',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 5,
    seatY: 7,
    rowIndex: 5,
    columnIndex: 7,
    status: '1',
    id: 'seat-5-7',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 5,
    seatY: 8,
    rowIndex: 5,
    columnIndex: 8,
    status: '1',
    id: 'seat-5-8',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 5,
    seatY: 9,
    rowIndex: 5,
    columnIndex: 9,
    status: '1',
    id: 'seat-5-9',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 5,
    seatY: 10,
    rowIndex: 5,
    columnIndex: 10,
    status: '1',
    id: 'seat-5-10',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 6,
    seatY: 1,
    rowIndex: 6,
    columnIndex: 1,
    status: '1',
    id: 'seat-6-1',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 6,
    seatY: 2,
    rowIndex: 6,
    columnIndex: 2,
    status: '1',
    id: 'seat-6-2',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 6,
    seatY: 3,
    rowIndex: 6,
    columnIndex: 3,
    status: '1',
    id: 'seat-6-3',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 6,
    seatY: 4,
    rowIndex: 6,
    columnIndex: 4,
    status: '1',
    id: 'seat-6-4',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 6,
    seatY: 5,
    rowIndex: 6,
    columnIndex: 5,
    status: '1',
    id: 'seat-6-5',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 6,
    seatY: 6,
    rowIndex: 6,
    columnIndex: 6,
    status: '1',
    id: 'seat-6-6',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 6,
    seatY: 7,
    rowIndex: 6,
    columnIndex: 7,
    status: '1',
    id: 'seat-6-7',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 6,
    seatY: 8,
    rowIndex: 6,
    columnIndex: 8,
    status: '1',
    id: 'seat-6-8',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 6,
    seatY: 9,
    rowIndex: 6,
    columnIndex: 9,
    status: '1',
    id: 'seat-6-9',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 6,
    seatY: 10,
    rowIndex: 6,
    columnIndex: 10,
    status: '1',
    id: 'seat-6-10',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 7,
    seatY: 1,
    rowIndex: 7,
    columnIndex: 1,
    status: '1',
    id: 'seat-7-1',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 7,
    seatY: 2,
    rowIndex: 7,
    columnIndex: 2,
    status: '1',
    id: 'seat-7-2',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 7,
    seatY: 3,
    rowIndex: 7,
    columnIndex: 3,
    status: '1',
    id: 'seat-7-3',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 7,
    seatY: 4,
    rowIndex: 7,
    columnIndex: 4,
    status: '1',
    id: 'seat-7-4',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 7,
    seatY: 5,
    rowIndex: 7,
    columnIndex: 5,
    status: '1',
    id: 'seat-7-5',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 7,
    seatY: 6,
    rowIndex: 7,
    columnIndex: 6,
    status: '1',
    id: 'seat-7-6',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 7,
    seatY: 7,
    rowIndex: 7,
    columnIndex: 7,
    status: '1',
    id: 'seat-7-7',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 7,
    seatY: 8,
    rowIndex: 7,
    columnIndex: 8,
    status: '1',
    id: 'seat-7-8',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 7,
    seatY: 9,
    rowIndex: 7,
    columnIndex: 9,
    status: '1',
    id: 'seat-7-9',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 7,
    seatY: 10,
    rowIndex: 7,
    columnIndex: 10,
    status: '1',
    id: 'seat-7-10',
    color: '#979797',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 8,
    seatY: 1,
    rowIndex: 8,
    columnIndex: 1,
    status: '0',
    id: 'seat-8-1',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 8,
    seatY: 2,
    rowIndex: 8,
    columnIndex: 2,
    status: '0',
    id: 'seat-8-2',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 8,
    seatY: 3,
    rowIndex: 8,
    columnIndex: 3,
    status: '0',
    id: 'seat-8-3',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 8,
    seatY: 4,
    rowIndex: 8,
    columnIndex: 4,
    status: '0',
    id: 'seat-8-4',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 8,
    seatY: 5,
    rowIndex: 8,
    columnIndex: 5,
    status: '0',
    id: 'seat-8-5',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 8,
    seatY: 6,
    rowIndex: 8,
    columnIndex: 6,
    status: '0',
    id: 'seat-8-6',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 8,
    seatY: 7,
    rowIndex: 8,
    columnIndex: 7,
    status: '0',
    id: 'seat-8-7',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 8,
    seatY: 8,
    rowIndex: 8,
    columnIndex: 8,
    status: '0',
    id: 'seat-8-8',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 8,
    seatY: 9,
    rowIndex: 8,
    columnIndex: 9,
    status: '0',
    id: 'seat-8-9',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 8,
    seatY: 10,
    rowIndex: 8,
    columnIndex: 10,
    status: '0',
    id: 'seat-8-10',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 9,
    seatY: 1,
    rowIndex: 9,
    columnIndex: 1,
    status: '0',
    id: 'seat-9-1',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 9,
    seatY: 2,
    rowIndex: 9,
    columnIndex: 2,
    status: '0',
    id: 'seat-9-2',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 9,
    seatY: 3,
    rowIndex: 9,
    columnIndex: 3,
    status: '0',
    id: 'seat-9-3',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 9,
    seatY: 4,
    rowIndex: 9,
    columnIndex: 4,
    status: '0',
    id: 'seat-9-4',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 9,
    seatY: 5,
    rowIndex: 9,
    columnIndex: 5,
    status: '0',
    id: 'seat-9-5',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 9,
    seatY: 6,
    rowIndex: 9,
    columnIndex: 6,
    status: '0',
    id: 'seat-9-6',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 9,
    seatY: 7,
    rowIndex: 9,
    columnIndex: 7,
    status: '0',
    id: 'seat-9-7',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 9,
    seatY: 8,
    rowIndex: 9,
    columnIndex: 8,
    status: '0',
    id: 'seat-9-8',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 9,
    seatY: 9,
    rowIndex: 9,
    columnIndex: 9,
    status: '0',
    id: 'seat-9-9',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 9,
    seatY: 10,
    rowIndex: 9,
    columnIndex: 10,
    status: '0',
    id: 'seat-9-10',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 10,
    seatY: 1,
    rowIndex: 10,
    columnIndex: 1,
    status: '0',
    id: 'seat-10-1',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 10,
    seatY: 2,
    rowIndex: 10,
    columnIndex: 2,
    status: '0',
    id: 'seat-10-2',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 10,
    seatY: 3,
    rowIndex: 10,
    columnIndex: 3,
    status: '0',
    id: 'seat-10-3',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 10,
    seatY: 4,
    rowIndex: 10,
    columnIndex: 4,
    status: '0',
    id: 'seat-10-4',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 10,
    seatY: 5,
    rowIndex: 10,
    columnIndex: 5,
    status: '0',
    id: 'seat-10-5',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 10,
    seatY: 6,
    rowIndex: 10,
    columnIndex: 6,
    status: '0',
    id: 'seat-10-6',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 10,
    seatY: 7,
    rowIndex: 10,
    columnIndex: 7,
    status: '0',
    id: 'seat-10-7',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 10,
    seatY: 8,
    rowIndex: 10,
    columnIndex: 8,
    status: '0',
    id: 'seat-10-8',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 10,
    seatY: 9,
    rowIndex: 10,
    columnIndex: 9,
    status: '0',
    id: 'seat-10-9',
    color: '#fff',
  },
  {
    shape: 'rect',
    size: 30,
    type: 'seat',
    seatX: 10,
    seatY: 10,
    rowIndex: 10,
    columnIndex: 10,
    status: '0',
    id: 'seat-10-10',
    color: '#fff',
  },
];

class Home extends React.Component {
  state = {
    seatCreateVisbile: false,
    seatUpdateVisible: false,
  };

  showSeatCreateModal = (e) => {
    e.preventDefault();
    this.setState({ seatCreateVisbile: true });
  };

  showSeatUpdateModal = (e) => {
    e.preventDefault();
    this.setState({ seatUpdateVisible: true });
  };

  hideSeatCreateModal = (e) => {
    e.preventDefault();
    this.setState({ seatCreateVisbile: false });
  };

  hideSeatUpdateModal = (e) => {
    e.preventDefault();
    this.setState({ seatUpdateVisible: false });
  };

  handelDataSave = (data) => {
    console.log(data);
  };

  render() {
    const { seatCreateVisbile, seatUpdateVisible } = this.state;
    return (
      <div style={{ padding: 30 }}>
        <Button onClick={this.showSeatCreateModal}>座位生成</Button>
        <Button onClick={this.showSeatUpdateModal}>座位编辑</Button>
        <Modal
          title="座位编辑"
          visible={seatUpdateVisible}
          onCancel={e => this.hideSeatUpdateModal(e, false)}
          width={1200}
          destroyOnClose
          style={{ top: 20, width: 800 }}
          footer={false}
        >
          <SeatUpdate
            color={'#D03838'}
            performPackageId={'abe123'}
            data={dataJson}
            onSave={this.handelDataSave}
          />
        </Modal>
        <Modal
          title="座位生成"
          visible={seatCreateVisbile}
          destroyOnClose
          onCancel={e => this.hideSeatCreateModal(e, false)}
          width={1200}
          style={{ top: 20, width: 800 }}
          footer={false}
        >
          <SeatCreate row={10} col={10} onSave={this.handelDataSave} />
        </Modal>
      </div>
    );
  }
}

export default Home;
