import React from 'react';
import { Button, Modal } from 'antd';
import SeatSetModal from '../components/SeatCanvas';

const dataJson = {
  nodes: [
    {
      shape: 'text',
      size: 20,
      id: 'label-0-0',
      x: 0,
      y: 0,
      label: 0,
      type: 'label',
    },
    {
      shape: 'text',
      size: 20,
      id: 'label-0-1',
      x: 0,
      y: 40,
      label: 1,
      type: 'label',
    },
    {
      shape: 'text',
      size: 20,
      id: 'label-0-2',
      x: 0,
      y: 80,
      label: 2,
      type: 'label',
    },
    {
      shape: 'text',
      size: 20,
      id: 'label-0-3',
      x: 0,
      y: 120,
      label: 3,
      type: 'label',
    },
    {
      shape: 'text',
      size: 20,
      id: 'label-0-4',
      x: 0,
      y: 160,
      label: 4,
      type: 'label',
    },
    {
      shape: 'text',
      size: 20,
      id: 'label-0-5',
      x: 0,
      y: 200,
      label: 5,
      type: 'label',
    },
    {
      shape: 'text',
      size: 20,
      id: 'label-0-6',
      x: 0,
      y: 240,
      label: 6,
      type: 'label',
    },
    {
      shape: 'text',
      size: 20,
      id: 'label-0-7',
      x: 0,
      y: 280,
      label: 7,
      type: 'label',
    },
    {
      shape: 'text',
      size: 20,
      id: 'label-0-8',
      x: 0,
      y: 320,
      label: 8,
      type: 'label',
    },
    {
      shape: 'text',
      size: 20,
      id: 'label-0-9',
      x: 0,
      y: 360,
      label: 9,
      type: 'label',
    },
    {
      shape: 'text',
      size: 20,
      id: 'label-0-10',
      x: 0,
      y: 400,
      label: 10,
      type: 'label',
    },
    {
      shape: 'text',
      size: 20,
      id: 'label-1-0',
      x: 40,
      y: 0,
      label: 1,
      type: 'label',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 1,
      seatY: 1,
      rowIndex: 1,
      columnIndex: 1,
      status: '1',
      id: 'seat-1-1',
      x: 40,
      y: 40,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 1,
      seatY: 2,
      rowIndex: 1,
      columnIndex: 2,
      status: '1',
      id: 'seat-1-2',
      x: 40,
      y: 80,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 1,
      seatY: 3,
      rowIndex: 1,
      columnIndex: 3,
      status: '1',
      id: 'seat-1-3',
      x: 40,
      y: 120,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 1,
      seatY: 4,
      rowIndex: 1,
      columnIndex: 4,
      status: '1',
      id: 'seat-1-4',
      x: 40,
      y: 160,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 1,
      seatY: 5,
      rowIndex: 1,
      columnIndex: 5,
      status: '1',
      id: 'seat-1-5',
      x: 40,
      y: 200,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 1,
      seatY: 6,
      rowIndex: 1,
      columnIndex: 6,
      status: '1',
      id: 'seat-1-6',
      x: 40,
      y: 240,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 1,
      seatY: 7,
      rowIndex: 1,
      columnIndex: 7,
      status: '1',
      id: 'seat-1-7',
      x: 40,
      y: 280,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 1,
      seatY: 8,
      rowIndex: 1,
      columnIndex: 8,
      status: '1',
      id: 'seat-1-8',
      x: 40,
      y: 320,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 1,
      seatY: 9,
      rowIndex: 1,
      columnIndex: 9,
      status: '1',
      id: 'seat-1-9',
      x: 40,
      y: 360,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 1,
      seatY: 10,
      rowIndex: 1,
      columnIndex: 10,
      status: '1',
      id: 'seat-1-10',
      x: 40,
      y: 400,
      color: '#979797',
    },
    {
      shape: 'text',
      size: 20,
      id: 'label-2-0',
      x: 80,
      y: 0,
      label: 2,
      type: 'label',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 2,
      seatY: 1,
      rowIndex: 2,
      columnIndex: 1,
      status: '1',
      id: 'seat-2-1',
      x: 80,
      y: 40,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 2,
      seatY: 2,
      rowIndex: 2,
      columnIndex: 2,
      status: '1',
      id: 'seat-2-2',
      x: 80,
      y: 80,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 2,
      seatY: 3,
      rowIndex: 2,
      columnIndex: 3,
      status: '1',
      id: 'seat-2-3',
      x: 80,
      y: 120,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 2,
      seatY: 4,
      rowIndex: 2,
      columnIndex: 4,
      status: '1',
      id: 'seat-2-4',
      x: 80,
      y: 160,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 2,
      seatY: 5,
      rowIndex: 2,
      columnIndex: 5,
      status: '1',
      id: 'seat-2-5',
      x: 80,
      y: 200,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 2,
      seatY: 6,
      rowIndex: 2,
      columnIndex: 6,
      status: '1',
      id: 'seat-2-6',
      x: 80,
      y: 240,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 2,
      seatY: 7,
      rowIndex: 2,
      columnIndex: 7,
      status: '1',
      id: 'seat-2-7',
      x: 80,
      y: 280,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 2,
      seatY: 8,
      rowIndex: 2,
      columnIndex: 8,
      status: '1',
      id: 'seat-2-8',
      x: 80,
      y: 320,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 2,
      seatY: 9,
      rowIndex: 2,
      columnIndex: 9,
      status: '1',
      id: 'seat-2-9',
      x: 80,
      y: 360,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 2,
      seatY: 10,
      rowIndex: 2,
      columnIndex: 10,
      status: '1',
      id: 'seat-2-10',
      x: 80,
      y: 400,
      color: '#979797',
    },
    {
      shape: 'text',
      size: 20,
      id: 'label-3-0',
      x: 120,
      y: 0,
      label: 3,
      type: 'label',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 3,
      seatY: 1,
      rowIndex: 3,
      columnIndex: 1,
      status: '1',
      id: 'seat-3-1',
      x: 120,
      y: 40,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 3,
      seatY: 2,
      rowIndex: 3,
      columnIndex: 2,
      status: '1',
      id: 'seat-3-2',
      x: 120,
      y: 80,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 3,
      seatY: 3,
      rowIndex: 3,
      columnIndex: 3,
      status: '1',
      id: 'seat-3-3',
      x: 120,
      y: 120,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 3,
      seatY: 4,
      rowIndex: 3,
      columnIndex: 4,
      status: '1',
      id: 'seat-3-4',
      x: 120,
      y: 160,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 3,
      seatY: 5,
      rowIndex: 3,
      columnIndex: 5,
      status: '1',
      id: 'seat-3-5',
      x: 120,
      y: 200,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 3,
      seatY: 6,
      rowIndex: 3,
      columnIndex: 6,
      status: '1',
      id: 'seat-3-6',
      x: 120,
      y: 240,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 3,
      seatY: 7,
      rowIndex: 3,
      columnIndex: 7,
      status: '1',
      id: 'seat-3-7',
      x: 120,
      y: 280,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 3,
      seatY: 8,
      rowIndex: 3,
      columnIndex: 8,
      status: '1',
      id: 'seat-3-8',
      x: 120,
      y: 320,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 3,
      seatY: 9,
      rowIndex: 3,
      columnIndex: 9,
      status: '1',
      id: 'seat-3-9',
      x: 120,
      y: 360,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 3,
      seatY: 10,
      rowIndex: 3,
      columnIndex: 10,
      status: '1',
      id: 'seat-3-10',
      x: 120,
      y: 400,
      color: '#979797',
    },
    {
      shape: 'text',
      size: 20,
      id: 'label-4-0',
      x: 160,
      y: 0,
      label: 4,
      type: 'label',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 4,
      seatY: 1,
      rowIndex: 4,
      columnIndex: 1,
      status: '1',
      id: 'seat-4-1',
      x: 160,
      y: 40,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 4,
      seatY: 2,
      rowIndex: 4,
      columnIndex: 2,
      status: '1',
      id: 'seat-4-2',
      x: 160,
      y: 80,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 4,
      seatY: 3,
      rowIndex: 4,
      columnIndex: 3,
      status: '1',
      id: 'seat-4-3',
      x: 160,
      y: 120,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 4,
      seatY: 4,
      rowIndex: 4,
      columnIndex: 4,
      status: '1',
      id: 'seat-4-4',
      x: 160,
      y: 160,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 4,
      seatY: 5,
      rowIndex: 4,
      columnIndex: 5,
      status: '1',
      id: 'seat-4-5',
      x: 160,
      y: 200,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 4,
      seatY: 6,
      rowIndex: 4,
      columnIndex: 6,
      status: '1',
      id: 'seat-4-6',
      x: 160,
      y: 240,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 4,
      seatY: 7,
      rowIndex: 4,
      columnIndex: 7,
      status: '1',
      id: 'seat-4-7',
      x: 160,
      y: 280,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 4,
      seatY: 8,
      rowIndex: 4,
      columnIndex: 8,
      status: '1',
      id: 'seat-4-8',
      x: 160,
      y: 320,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 4,
      seatY: 9,
      rowIndex: 4,
      columnIndex: 9,
      status: '1',
      id: 'seat-4-9',
      x: 160,
      y: 360,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 4,
      seatY: 10,
      rowIndex: 4,
      columnIndex: 10,
      status: '1',
      id: 'seat-4-10',
      x: 160,
      y: 400,
      color: '#979797',
    },
    {
      shape: 'text',
      size: 20,
      id: 'label-5-0',
      x: 200,
      y: 0,
      label: 5,
      type: 'label',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 5,
      seatY: 1,
      rowIndex: 5,
      columnIndex: 1,
      status: '1',
      id: 'seat-5-1',
      x: 200,
      y: 40,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 5,
      seatY: 2,
      rowIndex: 5,
      columnIndex: 2,
      status: '1',
      id: 'seat-5-2',
      x: 200,
      y: 80,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 5,
      seatY: 3,
      rowIndex: 5,
      columnIndex: 3,
      status: '1',
      id: 'seat-5-3',
      x: 200,
      y: 120,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 5,
      seatY: 4,
      rowIndex: 5,
      columnIndex: 4,
      status: '1',
      id: 'seat-5-4',
      x: 200,
      y: 160,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 5,
      seatY: 5,
      rowIndex: 5,
      columnIndex: 5,
      status: '1',
      id: 'seat-5-5',
      x: 200,
      y: 200,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 5,
      seatY: 6,
      rowIndex: 5,
      columnIndex: 6,
      status: '1',
      id: 'seat-5-6',
      x: 200,
      y: 240,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 5,
      seatY: 7,
      rowIndex: 5,
      columnIndex: 7,
      status: '1',
      id: 'seat-5-7',
      x: 200,
      y: 280,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 5,
      seatY: 8,
      rowIndex: 5,
      columnIndex: 8,
      status: '1',
      id: 'seat-5-8',
      x: 200,
      y: 320,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 5,
      seatY: 9,
      rowIndex: 5,
      columnIndex: 9,
      status: '1',
      id: 'seat-5-9',
      x: 200,
      y: 360,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 5,
      seatY: 10,
      rowIndex: 5,
      columnIndex: 10,
      status: '1',
      id: 'seat-5-10',
      x: 200,
      y: 400,
      color: '#979797',
    },
    {
      shape: 'text',
      size: 20,
      id: 'label-6-0',
      x: 240,
      y: 0,
      label: 6,
      type: 'label',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 6,
      seatY: 1,
      rowIndex: 6,
      columnIndex: 1,
      status: '1',
      id: 'seat-6-1',
      x: 240,
      y: 40,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 6,
      seatY: 2,
      rowIndex: 6,
      columnIndex: 2,
      status: '1',
      id: 'seat-6-2',
      x: 240,
      y: 80,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 6,
      seatY: 3,
      rowIndex: 6,
      columnIndex: 3,
      status: '1',
      id: 'seat-6-3',
      x: 240,
      y: 120,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 6,
      seatY: 4,
      rowIndex: 6,
      columnIndex: 4,
      status: '1',
      id: 'seat-6-4',
      x: 240,
      y: 160,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 6,
      seatY: 5,
      rowIndex: 6,
      columnIndex: 5,
      status: '1',
      id: 'seat-6-5',
      x: 240,
      y: 200,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 6,
      seatY: 6,
      rowIndex: 6,
      columnIndex: 6,
      status: '1',
      id: 'seat-6-6',
      x: 240,
      y: 240,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 6,
      seatY: 7,
      rowIndex: 6,
      columnIndex: 7,
      status: '1',
      id: 'seat-6-7',
      x: 240,
      y: 280,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 6,
      seatY: 8,
      rowIndex: 6,
      columnIndex: 8,
      status: '1',
      id: 'seat-6-8',
      x: 240,
      y: 320,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 6,
      seatY: 9,
      rowIndex: 6,
      columnIndex: 9,
      status: '1',
      id: 'seat-6-9',
      x: 240,
      y: 360,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 6,
      seatY: 10,
      rowIndex: 6,
      columnIndex: 10,
      status: '1',
      id: 'seat-6-10',
      x: 240,
      y: 400,
      color: '#979797',
    },
    {
      shape: 'text',
      size: 20,
      id: 'label-7-0',
      x: 280,
      y: 0,
      label: 7,
      type: 'label',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 7,
      seatY: 1,
      rowIndex: 7,
      columnIndex: 1,
      status: '1',
      id: 'seat-7-1',
      x: 280,
      y: 40,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 7,
      seatY: 2,
      rowIndex: 7,
      columnIndex: 2,
      status: '1',
      id: 'seat-7-2',
      x: 280,
      y: 80,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 7,
      seatY: 3,
      rowIndex: 7,
      columnIndex: 3,
      status: '1',
      id: 'seat-7-3',
      x: 280,
      y: 120,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 7,
      seatY: 4,
      rowIndex: 7,
      columnIndex: 4,
      status: '1',
      id: 'seat-7-4',
      x: 280,
      y: 160,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 7,
      seatY: 5,
      rowIndex: 7,
      columnIndex: 5,
      status: '1',
      id: 'seat-7-5',
      x: 280,
      y: 200,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 7,
      seatY: 6,
      rowIndex: 7,
      columnIndex: 6,
      status: '1',
      id: 'seat-7-6',
      x: 280,
      y: 240,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 7,
      seatY: 7,
      rowIndex: 7,
      columnIndex: 7,
      status: '1',
      id: 'seat-7-7',
      x: 280,
      y: 280,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 7,
      seatY: 8,
      rowIndex: 7,
      columnIndex: 8,
      status: '1',
      id: 'seat-7-8',
      x: 280,
      y: 320,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 7,
      seatY: 9,
      rowIndex: 7,
      columnIndex: 9,
      status: '1',
      id: 'seat-7-9',
      x: 280,
      y: 360,
      color: '#979797',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 7,
      seatY: 10,
      rowIndex: 7,
      columnIndex: 10,
      status: '1',
      id: 'seat-7-10',
      x: 280,
      y: 400,
      color: '#979797',
    },
    {
      shape: 'text',
      size: 20,
      id: 'label-8-0',
      x: 320,
      y: 0,
      label: 8,
      type: 'label',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 8,
      seatY: 1,
      rowIndex: 8,
      columnIndex: 1,
      status: '0',
      id: 'seat-8-1',
      x: 320,
      y: 40,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 8,
      seatY: 2,
      rowIndex: 8,
      columnIndex: 2,
      status: '0',
      id: 'seat-8-2',
      x: 320,
      y: 80,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 8,
      seatY: 3,
      rowIndex: 8,
      columnIndex: 3,
      status: '0',
      id: 'seat-8-3',
      x: 320,
      y: 120,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 8,
      seatY: 4,
      rowIndex: 8,
      columnIndex: 4,
      status: '0',
      id: 'seat-8-4',
      x: 320,
      y: 160,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 8,
      seatY: 5,
      rowIndex: 8,
      columnIndex: 5,
      status: '0',
      id: 'seat-8-5',
      x: 320,
      y: 200,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 8,
      seatY: 6,
      rowIndex: 8,
      columnIndex: 6,
      status: '0',
      id: 'seat-8-6',
      x: 320,
      y: 240,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 8,
      seatY: 7,
      rowIndex: 8,
      columnIndex: 7,
      status: '0',
      id: 'seat-8-7',
      x: 320,
      y: 280,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 8,
      seatY: 8,
      rowIndex: 8,
      columnIndex: 8,
      status: '0',
      id: 'seat-8-8',
      x: 320,
      y: 320,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 8,
      seatY: 9,
      rowIndex: 8,
      columnIndex: 9,
      status: '0',
      id: 'seat-8-9',
      x: 320,
      y: 360,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 8,
      seatY: 10,
      rowIndex: 8,
      columnIndex: 10,
      status: '0',
      id: 'seat-8-10',
      x: 320,
      y: 400,
      color: '#fff',
    },
    {
      shape: 'text',
      size: 20,
      id: 'label-9-0',
      x: 360,
      y: 0,
      label: 9,
      type: 'label',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 9,
      seatY: 1,
      rowIndex: 9,
      columnIndex: 1,
      status: '0',
      id: 'seat-9-1',
      x: 360,
      y: 40,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 9,
      seatY: 2,
      rowIndex: 9,
      columnIndex: 2,
      status: '0',
      id: 'seat-9-2',
      x: 360,
      y: 80,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 9,
      seatY: 3,
      rowIndex: 9,
      columnIndex: 3,
      status: '0',
      id: 'seat-9-3',
      x: 360,
      y: 120,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 9,
      seatY: 4,
      rowIndex: 9,
      columnIndex: 4,
      status: '0',
      id: 'seat-9-4',
      x: 360,
      y: 160,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 9,
      seatY: 5,
      rowIndex: 9,
      columnIndex: 5,
      status: '0',
      id: 'seat-9-5',
      x: 360,
      y: 200,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 9,
      seatY: 6,
      rowIndex: 9,
      columnIndex: 6,
      status: '0',
      id: 'seat-9-6',
      x: 360,
      y: 240,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 9,
      seatY: 7,
      rowIndex: 9,
      columnIndex: 7,
      status: '0',
      id: 'seat-9-7',
      x: 360,
      y: 280,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 9,
      seatY: 8,
      rowIndex: 9,
      columnIndex: 8,
      status: '0',
      id: 'seat-9-8',
      x: 360,
      y: 320,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 9,
      seatY: 9,
      rowIndex: 9,
      columnIndex: 9,
      status: '0',
      id: 'seat-9-9',
      x: 360,
      y: 360,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 9,
      seatY: 10,
      rowIndex: 9,
      columnIndex: 10,
      status: '0',
      id: 'seat-9-10',
      x: 360,
      y: 400,
      color: '#fff',
    },
    {
      shape: 'text',
      size: 20,
      id: 'label-10-0',
      x: 400,
      y: 0,
      label: 10,
      type: 'label',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 10,
      seatY: 1,
      rowIndex: 10,
      columnIndex: 1,
      status: '0',
      id: 'seat-10-1',
      x: 400,
      y: 40,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 10,
      seatY: 2,
      rowIndex: 10,
      columnIndex: 2,
      status: '0',
      id: 'seat-10-2',
      x: 400,
      y: 80,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 10,
      seatY: 3,
      rowIndex: 10,
      columnIndex: 3,
      status: '0',
      id: 'seat-10-3',
      x: 400,
      y: 120,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 10,
      seatY: 4,
      rowIndex: 10,
      columnIndex: 4,
      status: '0',
      id: 'seat-10-4',
      x: 400,
      y: 160,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 10,
      seatY: 5,
      rowIndex: 10,
      columnIndex: 5,
      status: '0',
      id: 'seat-10-5',
      x: 400,
      y: 200,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 10,
      seatY: 6,
      rowIndex: 10,
      columnIndex: 6,
      status: '0',
      id: 'seat-10-6',
      x: 400,
      y: 240,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 10,
      seatY: 7,
      rowIndex: 10,
      columnIndex: 7,
      status: '0',
      id: 'seat-10-7',
      x: 400,
      y: 280,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 10,
      seatY: 8,
      rowIndex: 10,
      columnIndex: 8,
      status: '0',
      id: 'seat-10-8',
      x: 400,
      y: 320,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 10,
      seatY: 9,
      rowIndex: 10,
      columnIndex: 9,
      status: '0',
      id: 'seat-10-9',
      x: 400,
      y: 360,
      color: '#fff',
    },
    {
      shape: 'rect',
      size: 30,
      type: 'seat',
      seatX: 10,
      seatY: 10,
      rowIndex: 10,
      columnIndex: 10,
      status: '0',
      id: 'seat-10-10',
      x: 400,
      y: 400,
      color: '#fff',
    },
  ],
};

class Home extends React.Component {
  state = {
    setModalVisbile: true,
  };

  showSeatSetModal = (e) => {
    e.preventDefault();
    this.setState({ setModalVisbile: true });
  };

  hideSeatSetModal = (e) => {
    e.preventDefault();
    this.setState({ setModalVisbile: false });
  };

  render() {
    const { setModalVisbile } = this.state;
    return (
      <div style={{ padding: 30 }}>
        <Button onClick={this.showSeatSetModal}>座位编辑</Button>
        <Modal
          title="Basic Modal"
          visible={setModalVisbile}
          onOk={e => this.hideSeatSetModal(e, false)}
          onCancel={e => this.hideSeatSetModal(e, false)}
          width={1200}
          style={{ top: 20, width: 800 }}
          bodyStyle={{ height: 800 }}
        >
          <SeatSetModal
            row={10}
            col={10}
            type="area"
            color={'#D03838'}
            performPackageId={'abe123'}
            data={dataJson}
          />
        </Modal>
      </div>
    );
  }
}

export default Home;
